core/urls.py
from django.urls import path, include
from .views import HomeView,checkout,ItemDeatailView,\
    add_to_cart,delete_cart,OrderSummaryView,remove_single_item_from_cart,add_single_item_from_cart,\
    delete_cart_summary,PaymentView,add_copon,get_copon,RequestRefundView,ShowCategoury

urlpatterns = [
    path('',HomeView.as_view(),name='home'),
    path('product/<slug>/',ItemDeatailView.as_view(),name='product'),
    path('Checkout/',checkout.as_view(),name='checkout'),
    path('add-to-cart/<slug>/',add_to_cart,name='add-to-card'),
    path('delete-from-cart/<slug>/',delete_cart,name='delete-from-card'),
    path('order-summary/',OrderSummaryView.as_view(),name='order-summary'),
    path('remove-single-from-quantity/<slug>/',remove_single_item_from_cart,name='remove-single-form-cart'),
    path('add-single-from-quantity/<slug>/',add_single_item_from_cart,name='add-single-form-cart'),
    path('delete-from-cart-summary/<slug>/',delete_cart_summary,name='delete-from-cart-summary'),
    path('payment/<payment_option>/',PaymentView.as_view(),name='payment'),
    path('add-copon/',add_copon,name='add-copon'),
    path('request-refund/',RequestRefundView.as_view(),name='request-refund'),
    path('Categouty-filter/<cate>/',ShowCategoury,name='filterCate'),
]

djecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('',include('core.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django_countries.fields import CountryField
# Create your models here.

CATEGORY_CHOICES = (
    ('L','LG'),
    ('H','Huawei'),
    ('A','Apple'),
)


LABEL_CHOICES = (
    ('P','primary'),
    ('S','secondary'),
    ('D','danger'),
)
class Category(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title
class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True,null=True)
    # category = models.CharField(choices=CATEGORY_CHOICES,max_length=2,default='SW')
    category= models.ForeignKey(Category, on_delete=models.CASCADE)
    label = models.CharField(choices=LABEL_CHOICES,max_length=1,default='P')
    slug = models.SlugField(default='test-product')
    description = models.TextField(default='')
    quantity = models.IntegerField(default=1)
    image = models.ImageField(upload_to='products/',default=None,blank=True,null=True)
    def __str__(self):
        return self.title


    def get_category(self):
        CATEGORYS = []
        for c in CATEGORY_CHOICES:
            CATEGORYS.append(c[1])
        return CATEGORYS

    def get_absolute_url(self):
        return reverse('product',kwargs={
            'slug':self.slug
        })

    def get_add_to_card_url(self):
        return reverse('add-to-card',kwargs={
            'slug':self.slug
        })

    def delete_from_cart_url(self):
        return reverse('delete-from-card', kwargs={
            'slug': self.slug
        })




import  datetime
class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item,on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    
    def __str__(self):
        return f"{self.quantity} Of {self.item.title}"

    def get_total_item_price(self):

        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_discount_item_price() - self.get_total_item_price()

    # def get_final_price(self):
    #     if self.item.discount_price:
    #         return self.get_total_item_price()
    #     return self.get_total_item_price()

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL ,on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField(auto_now=True)
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey('BillingAddress',on_delete=models.SET_NULL,blank=True,null=True)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)
    copon = models.ForeignKey('Copun',models.SET_NULL,blank=True,null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_request = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)
    ref_code = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username


    def get_total_item_all_price(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_total_item_price()
        if self.copon:
            total -= self.copon.amount
        return total


class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL ,on_delete=models.CASCADE)
    street_address =  models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username


class Payment(models.Model):
    Stripe_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Copun(models.Model):
    code = models.CharField(max_length=50)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order,on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f'{self.pk}'

templates/_parts/_alerts.html
{% load static %}
{% if messages %}
    {% for message in messages %}
        <!-- Bootstrap core CSS -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

        <div id="message" class="container mt-5 pt-5">
            <div class="alert alert-success text-center alert-dismissible">
                <button class="close" type="button"><span>&times;</span></button>
                <strong>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}

                    {% else %}
                        {{ title }}

                    {% endif %}
                </strong>

                {{ message }}

            </div>
        </div>

    {% endfor %}

{% endif %}


<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script  type="text/javascript">
    setTimeout(function () {
        $('#message').slideDown('slow')
    }, 3000);
</script>
{#<script src="{% static 'js/main.js' %}"></script>#}

templates/_parts/categouries_nav.html
<nav class="navbar navbar-expand-lg navbar-light  lighten-3 mt-3 mb-5" style="background-color: #1c4960">

        <!-- Navbar brand -->
        <span class="navbar-brand" style="color: white;">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" style="color: white" href="{% url 'home' %}">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
        {% for cate in Category %}
            <li class="nav-item">
              <a class="nav-link" style="color: white" href="{% url 'filterCate' cate.title %}">{{cate.title}}</a>
            </li>
              {% endfor %}

{#            <li class="nav-item">#}
{#              <a class="nav-link" style="color: white" href="#">Huawei</a>#}
{#            </li>#}
{#            <li class="nav-item">#}
{#              <a class="nav-link" style="color: white" href="#">LG</a>#}
{#            </li>#}

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" style="color: white;" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>

templates/_parts/copon.html
 <div class="col-md-4 mb-4">

                <!-- Heading -->
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-muted">Your cart</span>
                    <span class="badge badge-secondary badge-pill">{{order.items.count}}</span>
                </h4>

                <!-- Cart -->
                <ul class="list-group mb-3 z-depth-1">
                    {% for item in orderitem.all %}
                        <li class="list-group-item d-flex justify-content-between lh-condensed">
                            <div>
                                <h6 class="my-0">{{item.item.title}}</h6>
                                <small class="text-muted"></small>
                            </div>
                            <span class="text-muted">{{ item.item.price }}</span>
                        </li>
                    {% endfor %}
                    {% if order.copon %}
                    <li class="list-group-item d-flex justify-content-between bg-light">
                      <div class="text-success">
                          <h6 class="my-1"><strong>Promo code</strong></h6>

                      </div>

                      <span class="text-success"><strong>{{ order.copon.amount }}</strong></span>

                    </li>
                {% endif %}
                    <li class="list-group-item d-flex justify-content-between">
                        <span>Total (USD)</span>
                        <strong>{{ order.get_total_item_all_price }}$</strong>
                    </li>
                </ul>
                <!-- Cart -->
            {% if ShowCoponForm %}
                <!-- Promo code -->

                <form class="card p-2" action="{% url 'add-copon' %}" method="post">
                    <div class="input-group">
{#                        <input type="text" class="form-control" placeholder="Promo code"#}
{#                               aria-label="Recipient's username"#}
{#                               aria-describedby="basic-addon2">#}
                        {{ coponForm.code }}
                        <div class="input-group-append">
                            <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
                        </div>
                    </div>
                    {% csrf_token %}
                </form>

                <!-- Promo code -->
            {% endif %}
            </div>

templates/_parts/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn">


    <!--/.Call to action-->

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="#" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>

templates/_parts/nav.html
{% load cart_template_tags %}
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="{% url 'home' %}" target="_blank">
        <strong class="blue-text">DJe-commerce</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">


        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">


        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'order-summary' %}">
              <span class="badge red z-depth-1 mr-1"> {{request.user | cart_item_count}} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>


            <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>

            {% else %}
            <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>



            <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
              <span class="clearfix d-none d-sm-inline-block"> SignUp </span>
            </a>
          </li>

            {% endif %}






        </ul>

      </div>

    </div>
  </nav>

templates/_parts/pagination.html
<nav class="d-flex justify-content-center wow fadeIn">
    {% if is_paginated %}
        <ul class="pagination pg-blue">

          <!--Arrow left-->
            {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
            {% endif %}

        {% for item in page_obj.paginator.page_range %}
        {% if page_obj.number == item  %}
          <li class="page-item active" >
            {% else %}
            <li class="page-item" >
          {% endif %}
            <a class="page-link" href="?page={{ item }}">{{ item }}
              <span class="sr-only"></span>
            </a>
          </li>
        {% endfor %}

            {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number  }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
                {% endif %}
        </ul>
    {% endif %}
      </nav>

templates/_parts/product.html
{% load static %}
<section class="text-center mb-4">

        <!--Grid row-->


        <!--Grid row-->
        <div class="row wow fadeIn">


          {% for item in items %}
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
               <img  src="{{ item.image.url }}" height="350" class="card-img-top"
                  alt="">
                <a href='{{ item.get_absolute_url }}'>
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="{{ item.get_absolute_url }}" class="grey-text">
                  <h5>{{item.title}}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{item.category}} <br>
                      <span class="badge badge-pill {{item.get_label_display}}-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                {% if item.discount_price %}
                <h4 class="font-weight-bold blue-text">
                  <del>{{item.discount_price}}$</del>
                </h4>
                <h4 class="font-weight-bold blue-text">
                  <strong>{{item.price}}$</strong>
                </h4>
                {% else %}
                <h4 class="font-weight-bold blue-text">
                  <strong>{{item.price}}$</strong>
                </h4>
                {% endif %}

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          <!--Grid column-->
        {% endfor %}

        </div>
        <!--Grid row-->

      </section>
      <!--Section: Products v.3-->

templates/_parts/slide.html
  <!--Carousel Wrapper-->
  <div id="carousel-example-1z" class="carousel slide carousel-slide pt-4" data-ride="carousel">

    <!--Indicators-->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-1z" data-slide-to="1"></li>
      <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol>
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

      <!--First slide-->
      <div class="carousel-item active">
        <div class="view" style="background-image: url('w.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Learn Bootstrap 4 with MDB</strong>
              </h1>

              <p>
                <strong>Best & free guide of responsive web design</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and
                  written versions
                  available. Create your own, stunning website.</strong>
              </p>

              <a target="_blank" href="#" class="btn btn-outline-white btn-lg">Start
                free tutorial
                <i class="fas fa-graduation-cap ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/First slide-->

      <!--Second slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('s.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>50% OFF Promoution</strong>
              </h1>



              <p class="mb-4 d-none d-md-block">
                <strong>Just you need to type "Stay At Home"</strong>
              </p>

              <a target="_blank" href="#" class="btn btn-outline-white btn-lg">Start
                free tutorial
                <i class="fas fa-graduation-cap ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Second slide-->

      <!--Third slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('e.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Learn Bootstrap 4 with MDB</strong>
              </h1>

              <p>
                <strong>Best & free guide of responsive web design</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and
                  written versions
                  available. Create your own, stunning website.</strong>
              </p>

              <a target="_blank" href="#" class="btn btn-outline-white btn-lg">Start
                free tutorial
                <i class="fas fa-graduation-cap ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Third slide-->

    </div>
    <!--/.Slides-->

    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->

  </div>

templates/_parts/stripe.html
<br><br>
<div class="sr-root">
      <div class="sr-main col-6 container card">

            <form method="post">
                <div class="container md-form">
                    <div class="row">
                    <div class="col-lg-4 col-md-12 mb-4">
                        <input class="form-control " placeholder="Card Nubmer"/>
                    </div>

                    <div class="col-lg-4 col-md-12 mb-6">
                        <input class="form-control " placeholder="CCVT"/>
                    </div>

                    <div class="col-lg-4 col-md-12 mb-8">
                        <input type="date" class="form-control " placeholder="Exp Date"/>
                    </div>

                    <button type="submit" class="btn btn-mdb-color col-xl ">Payment</button>

                </div>

                {% csrf_token %}
                    </div>
            </form>
        <div class="sr-result hidden">


        </div>
      </div>
</div>

<br><br>